title: Welcome to Jade Morrisonâ€™s Online Portfolio
description: Graduating from The College of St Scholastica
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
